### PR TITLE
Moved the Judging algorithm folder to the internal tools repo and fixed the extra name bug

### LINKED ISSUE #107: [Judging algo] Migrate Judging Algo Repo + Types Bug
Design doc for this refresh can be found [here](https://docs.google.com/document/d/1BvoLmseirhUWLc4H2NgZVYB84oxghCpwLqq0YBz4vC4/edit)
- Copy over the Judging Algorithm folder from the mono repo: https://github.com/HackBeanpot/mono-repo/tree/main/judging-algorithm
- Reproduce the steps from README and ensure you can get it locally working. Clean up the README document for accuracy and formatting as necessary
- Resolve the bug that HackerTeam currently consumes an unnecessary extra field `name` as described in `judging-algorithm/types.ts`.

### PR DESCRIPTION
**Pull request by Aaryan1203**
Added the judging algorithm folder to the internal tools repo and fixed the extra name bug

Fixes #107 

Changelist:
- Added the judging algorithm folder to the internal tools repo
- Got rid of the dummy field in the HackerField type definition

Tested:
- Checked if the hackerResults and the judge results were exactly the same before and after the field deletion

### CODE REVIEW

**Review by NelsonDong41 — APPROVED** [review]
Looks moved to me. Nice job

**Review by mike10911 — CHANGES_REQUESTED** [review]
Great job guys!!!! The only thing is that we don't want to push up the node modules to GitHub as they will be installed when running `yarn install`. Check to see if the `.gitignore` is properly excluding them

**Review by mike10911 — CHANGES_REQUESTED** [review]
Okay now that you removed the node modules it is failing on deployment! On Vercel, it says `Type error: Cannot find module 'csv-parse/sync' or its corresponding type declarations. `

I think when importing you have to use `csv-parse/lib/sync`! Try this out and see if it fixes the deployment issue! Also, you can check out why Vercel is failing by using the LastPass sign-in!

**Review by Mandy-cyber — APPROVED** [review]
We love a lil' move! LGTM

**Comment by alyssamui** [comment]
> Okay now that you removed the node modules it is failing on deployment! On Vercel, it says `Type error: Cannot find module 'csv-parse/sync' or its corresponding type declarations. `
> 
> I think when importing you have to use `csv-parse/lib/sync`! Try this out and see if it fixes the deployment issue! Also, you can check out why Vercel is failing by using the LastPass sign-in!

Looks like the issue is that when building this repo, Vercel only runs `yarn install` for the outermost `yarn.lock` and `package.lock` files. The `csv-parse` library that we use is only marked as a dependency from within the `judging-algorithm` folder. I was able to fix the issue by adding `csv-parse` as a dependency for the whole repo, but it's not the best solution since it isn't necessary for most of the repo. If it's possible to have Vercel not build the `judging-algorithm` folder, I think that would be a better fix. Otherwise, it is working now!

**Review by mike10911 — APPROVED** [review]
LGTM!!

**Pull request merged**
