### PR TITLE
Style fixes

### LINKED ISSUE #50: Email sender style updates
Some quick styling updates that we should probably make before we demo the email sender:

- [x] Make sure the font everywhere is Nunito - if not, change it to Nunito to match the rest of HackBeanpot's materials
- [x] Change the colors of the header with the sign out button to match HackBeanpot's color scheme. See the design team's brand figma: https://www.figma.com/file/k1hw7MbweTXbh9JkN6lsmM/Brand-Book---2020?node-id=0%3A1
- [x] Sign out button should be changed to yellow - the color the brand book specifies as the call to action button color 
- [x] Change header to be navy color 
- [x] Move sign out button to right
- [x] Add HBP logo on left over header

### PR DESCRIPTION
**Pull request by Dhivas-Sugumar**
Closes #50 

- Made sure the font is nunito across the board. 
- Changed the sign-out button color and moved it to the right. 
- Added HBP logo to the left of the header. 
- Changed the header color to teal (cause navy doesn't work with the logo oops)

image

### CODE REVIEW

**Review by surbhi-gulati — APPROVED** [review]
Looks 🔥! Description says navy bar, but color isn't matching. Please update one of these, personally I like current colors though!

**Comment by Dhivas-Sugumar** [comment]
It was supposed to be navy but that covered the logo so changed it to teal @surbhi-gulati .

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
NIce PR! The font looks like it's still not nunito in a lot of areas though
Screen Shot 2022-07-19 at 10 44 27 PM
 
Also, I realized that there actually is a white hackbeanpot logo in the main site 2022 repo which could be used with the navy background. We could also keep it as is - up to whatever you guys think would look better!
Screen Shot 2022-07-19 at 10 45 20 PM

**Review by karynayen — CHANGES_REQUESTED** [review]
I agree with Judy!! I think the white hbp logo will look a lot cleaner! Also either the teal or the navy looks good, but to be more consistent and maybe consider making the sign-in button and the header the same color? Also maybe make the text sign-out text white?

**Review by jzhzhang66 — APPROVED** [review]
AYYYY looks fire

**Review by karynayen — APPROVED** [review]
LOOKS AMAZINGGG

**Pull request merged**
