### PR TITLE
[Feature] Set up MongoDB to handle our data

### LINKED ISSUE #110: [Feature] Set up MongoDB to handle our data
Ticket 3: [design doc -- judging algo refresh](https://docs.google.com/document/d/1BvoLmseirhUWLc4H2NgZVYB84oxghCpwLqq0YBz4vC4/edit)

- a. Put out a `.env` file for the internal tools repo within the judging folder, that contains the necessary Mongo credentials for developing. Remember to NOT upload these anywhere online, including GitHub

```
# mongodb configuration
# if changing any of these, also re-configure cypress.json
# these are only used for dev (and running in CI on Github):
MONGO_DEV_PORT=27017
MONGO_DEV_USERNAME=**Extract string from .env file in the app portal**
MONGO_DEV_PASSWORD=**Extract string from .env file in the app portal**
# comment the above, and uncomment below when you want to test against prod db
#MONGO_SERVER_DBNAME=**Extract string from .env file in the app portal**
#MONGO_PROD_CONNECTION_STRING=**Extract string from .env file in the app portal**
````

- b. Database name: Judging
- c. Collections: Teams, Judges, Rooms, RotationTimes
- d. Insert mock data in to the database

1. Use the pre-existing CSV files for judges, rooms and hackers found within the internal-tools repository
2. Create an additional CSV file for rotation times

Upload this data to MongoDB
Push the data up to internal-tools repository so that when tables get dropped, we have this for easy access

- e. In the internal-tools repository, create a Mongo Schema for each of the 4 collection types within a folder called `data/schemas`. Call each file `hackers-schema.ts`, etc. Within each schema, make all fields required. Here is an example of what your schema files will look like:

```
import mongoose from "mongoose";

export const groupsSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    description: { type: String, required: true },
    image: { type: String, required: true },
  },
  { collection: "groups" }
);
export default groupsSchema;
```

### PR DESCRIPTION
**Pull request by Aaryan1203**
Set up MongoDB to handle data

Fixes #110
Notes: 

- Created a csv file to store the MongoDB username and passwords
- Created a new Database in mongoDB
- Created four new collections and populated the teams, rooms, and judges collections
- Created a csv file for rotation items
- Created four schema files for each of the collections

Screenshots of the database:

image

image

image

### CODE REVIEW

**Review by kzeng24 — CHANGES_REQUESTED** [review]
Great work! 
Remember to remove the yarn.lock file and include the csv file that stores the MongoDB username and passwords!

**Comment by surbhi-gulati** [comment]
@kzeng24 These two callouts actually don't happen to apply but I just wanted to explain why so that we can all know moving forward -- but thanks for catching stuff on here, attentive eye!
- mongo credentials should *never* be pushed up, there shouldn't be a CSV file with these. All credentials should always go in `.env` to avoid pushing up. Other files can read it from our environment configuration without exposing info externally this way
- we must include `yarn.lock`, this is actually required for yarn installing and keeping dependencies in sync! it is `package-lock` that we want to put in to `.gitignore`, which is used when we deal with npm as our package manager

**Review by surbhi-gulati — APPROVED** [review]
@Aaryan1203 @alyssamui on that note please delete the CSV with mongo stuff locally too, but PR LGTM! Great work on this ticket:)

**Review by Mandy-cyber — APPROVED** [review]
LGTM! and thank you Katherine and Surbhi for that info about yarn.lock and the csv file--very informative 👯‍♀️

**Review by mike10911 — APPROVED** [review]
Wow guys this looks great! LGTM

**Review by NelsonDong41 — APPROVED** [review]
Looks good!

**Review by kzeng24 — APPROVED** [review]

**Pull request merged**
